version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:4000/api
  backend:
    build: ./kanban-apis
    ports:
      - "4000:4000"
    environment:
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_DATABASE=kanban
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
